format_version: v1.0
type: UniqueComponent
attributes: {id: dac}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DAC_DITHERING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: DAC_OUTPUT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dac, value: '2'}
- type: ElementPosition
  attributes: {x: '17', y: '63', id: dac}
