files:
- generatedChecksum: E45D1648EFC10229D7BE94DB19221FF7
  logicalPath: config\sam_c21n_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E45D1648EFC10229D7BE94DB19221FF7
- generatedChecksum: E738B6F44E95158DF60114B207955FAA
  logicalPath: config\sam_c21n_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E738B6F44E95158DF60114B207955FAA
- generatedChecksum: 4ABCE18A83255B644E0CB5CD765E7D54
  logicalPath: config\sam_c21n_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4ABCE18A83255B644E0CB5CD765E7D54
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_c21n_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: CC7D9611C3805535BC0360B2825494D7
  logicalPath: config\sam_c21n_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: CC7D9611C3805535BC0360B2825494D7
- generatedChecksum: 67DE290F9349D3F39F70AF15BBDACC1C
  logicalPath: config\sam_c21n_xpro\peripheral\eic
  name: plib_eic.c
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67DE290F9349D3F39F70AF15BBDACC1C
- generatedChecksum: 0811C3D935E6B01573434DBD54E4BABE
  logicalPath: config\sam_c21n_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0811C3D935E6B01573434DBD54E4BABE
- generatedChecksum: F9AA498D2DB20E7E1CEAFA0BD65BC0E6
  logicalPath: config\sam_c21n_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: F9AA498D2DB20E7E1CEAFA0BD65BC0E6
- generatedChecksum: 4DEE6D6F57FDB55F41831811E57118C1
  logicalPath: config\sam_c21n_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4DEE6D6F57FDB55F41831811E57118C1
- generatedChecksum: 2645E564BD945DAED1424FD8D7B39330
  logicalPath: config\sam_c21n_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2645E564BD945DAED1424FD8D7B39330
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_c21n_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 5A11AA1FDDF9F0E73B6C301368AC7CA3
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A11AA1FDDF9F0E73B6C301368AC7CA3
- generatedChecksum: 1FC17629B34A65B5263EB38F15B78374
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1FC17629B34A65B5263EB38F15B78374
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 5AAF3B829C83D883B06D3F334EEC9452
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: can.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5AAF3B829C83D883B06D3F334EEC9452
- generatedChecksum: B09070B7DD16FD62BDE35A43ED0ECF42
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ccl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B09070B7DD16FD62BDE35A43ED0ECF42
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 37B855C3B115037B7477C3B54FF5CEE7
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 37B855C3B115037B7477C3B54FF5CEE7
- generatedChecksum: 92BCFA7CA693C56E7128CEA17822A1E5
  logicalPath: config\sam_c21n_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 92BCFA7CA693C56E7128CEA17822A1E5
- generatedChecksum: 08797D9E3872E4E9460E8BABBC7A835E
  logicalPath: config\sam_c21n_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 08797D9E3872E4E9460E8BABBC7A835E
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_c21n_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: AB529AAE2090CC7FE1A71093085CCFA2
  logicalPath: config\sam_c21n_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: AB529AAE2090CC7FE1A71093085CCFA2
- generatedChecksum: 00C5596E431499F03B918FEAE49A0DE6
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: divas.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 00C5596E431499F03B918FEAE49A0DE6
- generatedChecksum: 1E71642DD2ED9F76CF1DA2656A1D3912
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E71642DD2ED9F76CF1DA2656A1D3912
- generatedChecksum: 5B432D6C2727D42D994888527F582A0C
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5B432D6C2727D42D994888527F582A0C
- generatedChecksum: 13019E7960A453D60A452E9E9CFBF3B1
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 13019E7960A453D60A452E9E9CFBF3B1
- generatedChecksum: CF0980937FC04E0DAF71821DA38B0B89
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF0980937FC04E0DAF71821DA38B0B89
- generatedChecksum: 56ED9C4BB56E744FA794595A91E2C552
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: freqm.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 56ED9C4BB56E744FA794595A91E2C552
- generatedChecksum: C41B1C921B7B19E2391E3758EE67A074
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C41B1C921B7B19E2391E3758EE67A074
- generatedChecksum: B4D335F0A2FE10A54305E7D13944AEB5
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B4D335F0A2FE10A54305E7D13944AEB5
- generatedChecksum: 5370BD00C59B7266E247670823C79B2C
  logicalPath: config\sam_c21n_xpro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5370BD00C59B7266E247670823C79B2C
- generatedChecksum: 1DF1DD101F6D3E94C080A7192D393CC4
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: mclk.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1DF1DD101F6D3E94C080A7192D393CC4
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 1A444CD55FBEF78C4D86CA91488A1B2B
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1A444CD55FBEF78C4D86CA91488A1B2B
- generatedChecksum: F53BAA34BF2DC8BA0F5CABA5D1A6B4D0
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F53BAA34BF2DC8BA0F5CABA5D1A6B4D0
- generatedChecksum: AC130EB1BB50064A8D12794CA60F4A59
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: osc32kctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AC130EB1BB50064A8D12794CA60F4A59
- generatedChecksum: E1265F554F5D2EB503F06313F16AF175
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: oscctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E1265F554F5D2EB503F06313F16AF175
- generatedChecksum: CF2972504591E8A971E6DB73EA09EA72
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF2972504591E8A971E6DB73EA09EA72
- generatedChecksum: 0416F129713FDF989ACC1FC57065125C
  logicalPath: config\sam_c21n_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 0416F129713FDF989ACC1FC57065125C
- generatedChecksum: D6E3678878E5746A2D7AA2F93E6D3D79
  logicalPath: config\sam_c21n_xpro\peripheral\eic
  name: plib_eic.h
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: HEADER
  userChecksum: D6E3678878E5746A2D7AA2F93E6D3D79
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_c21n_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 3B509F96A28A3B2A3FDA7473BC7C6544
  logicalPath: config\sam_c21n_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 3B509F96A28A3B2A3FDA7473BC7C6544
- generatedChecksum: A7AAAC0BED0F5F5796300F44190E2725
  logicalPath: config\sam_c21n_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: A7AAAC0BED0F5F5796300F44190E2725
- generatedChecksum: 6BF0443303BC84911AA77A6DC63121FB
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6BF0443303BC84911AA77A6DC63121FB
- generatedChecksum: 204427AE87F9A3848BA68E545681A39E
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 204427AE87F9A3848BA68E545681A39E
- generatedChecksum: 45105DA01030929736A0619142433071
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 45105DA01030929736A0619142433071
- generatedChecksum: 0B036E93F3B47007B175F37B6AC43596
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0B036E93F3B47007B175F37B6AC43596
- generatedChecksum: 364F89B99F14F774964FEF4400F95231
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 364F89B99F14F774964FEF4400F95231
- generatedChecksum: 85B1C6619285F00204D544FFB9488BD8
  logicalPath: packs\ATSAMC21N18A_DFP
  name: samc21n18a.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 85B1C6619285F00204D544FFB9488BD8
- generatedChecksum: FE2596FDA5D7CA449E5AB034DE301A2A
  logicalPath: packs\ATSAMC21N18A_DFP\pio
  name: samc21n18a.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: FE2596FDA5D7CA449E5AB034DE301A2A
- generatedChecksum: 3F53E80D3E935639E20475352E3E26DE
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: sdadc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F53E80D3E935639E20475352E3E26DE
- generatedChecksum: A29C76FBDF1228BA8621D402367CD15C
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A29C76FBDF1228BA8621D402367CD15C
- generatedChecksum: 2F2EF2FE010D71F9431397EBA3F56607
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2F2EF2FE010D71F9431397EBA3F56607
- generatedChecksum: 1C88891EA41DC4285FA93DA19923E555
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C88891EA41DC4285FA93DA19923E555
- generatedChecksum: 50CA1B3C5DE73CE17DB654CF9C38466E
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 50CA1B3C5DE73CE17DB654CF9C38466E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_c21n_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 5734F74138736E7EF09597F806F3CCD1
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tsens.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5734F74138736E7EF09597F806F3CCD1
- generatedChecksum: 06B2955CF46E4039C745E91682394D29
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 06B2955CF46E4039C745E91682394D29
- generatedChecksum: 25E15B2B6AF4BDB7B1AE2D2CB5B6BBEA
  logicalPath: config\sam_c21n_xpro
  name: ATSAMC21N18A.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 25E15B2B6AF4BDB7B1AE2D2CB5B6BBEA
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_c21n_xpro;../src/packs/ATSAMC21N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_c21n_xpro;../src/packs/ATSAMC21N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
