format_version: v1.0
type: UniqueComponent
attributes: {id: divas}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DIVAS_DIV_OVERLOAD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '91', y: '106', id: divas}
