format_version: v1.0
type: UniqueComponent
attributes: {id: sdadc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SDADC_AUTO_SEQUENCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: SDADC_CONV_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 85.0 uS ****'}
  - type: KeyValueSet
    attributes: {id: SDADC_CTRLB_OSR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: SDADC_CTRLB_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: SDADC_INPUTCTRL_MUXSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: SDADC_REFCTRL_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: SDADC_TRIGGER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '180', y: '99', id: sdadc}
