format_version: v1.0
configName: sam_c21n_xpro
folderName: sam_c21n_xpro
frameworkPath: E:\Harmony3
processor: ATSAMC21N18A
projectName: sam_c21n_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMC21_DFP\3.8.119\samc21n\atdf\ATSAMC21N18A.atdf
